# Site settings
title: Toronto Crypto
email: info@torontocrypto.org
description: >
  Home of the Toronto CryptoParty, a social movement to reclaim digital privacy.
url: "https://torontocrypto.org"
baseurl: ""
twitter_username: TorontoCrypto
github_username: torontocrypto

# Build settings
markdown: kramdown

exclude:
    - vendor
