# Site settings
title: Toronto Crypto
email: info@torontocrypto.org
description: Toronto's Privacy Advocacy
url: "https://torontocrypto.org"
baseurl: ""
twitter_username: TorontoCrypto
github_username: torontocrypto

# Build settings
markdown: kramdown

exclude:
    - vendor
