# Site settings
title: Toronto Crypto
email: info@torontocrypto.org
description: > # this means to ignore newlines until "baseurl:"
  Home of the Toronto CryptoParty, a social movement to reclaim digital privacy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://torontocrypto.org" # the base hostname & protocol for your site
twitter_username: TorontoCrypto
github_username: torontocrypto

# Build settings
markdown: kramdown

exclude:
    - vendor
